package main

import "app/interfaces"

func main() {
	// functions.Calc()
	// interfaces.Football()
	// pointers.Pointer1()
	// slicespkg.Slice1()
	// concurrency.FetchLineByLine()
	// concurrency.PromiseAllLikeFunctionWithWG()
	// concurrency.PromiseAllLikeFunctionWithUnbuffCh()
	// concurrency.PromiseAllLikeFunctionWithBuffCh()
	// concurrency.Pipeline()
	// internals.CaptLoopVars()
	// users := concurrency.MakeUsersList(50)
	// semaphore.DeactivateUsersSemaphore(users, 10)
	// workerpool.DeactivateUsersWorkerPool(users, 10)
	// semaphore.Semaphore2()
	// workerpool.WorkerPool2()
	// concurrency.Select()
	// concurrency.WithErrorGroup()
	// concurrency.ContextConcurrencyTimeout()
	// faninfanout.FanInFanOutExample2()
	// faninfanout.FanInFanOutExampleEx()
	// pool.SyncPoolExample()
	// once.OnceExample()
	// datarace.DataRace()
	// datarace.DataRaceEliminated()
	// workerpool.WorkerPool3()
	// projects.IncomeCalculator()
	// projects.ProducerConsumerProblem()
	// projects.DiningPhilosophers()
	// projects.ArmyCommunication()
	// projects.SleepingBarber()
	// projects.ChatServerMain()
	// projects.UseCache()
	interfaces.UseTypeAssertion()
	interfaces.UseTypeSwitch()

}
